### ISSUE TITLE
CLI image upload no longer works in Magento 2.3.x

### ISSUE THREAD

**Issue by chris-pook** [cloudinary/cloudinary_magento2#26] opened 2019-05-08 15:14 UTC
As of Magento 2.3.0 a check has been added to prevent access to files outside the Magento root:

https://github.com/magento/magento2/commit/7a1cbccf264c573a9e4780c91f2dbf3d2f2e3d87#diff-ba775b1202fb89f4927b36e854a782bfR123

This is causing the `./bin/magento cloudinary:upload:all` command to fail with the following message:  

`Path "/var/www/magento.loc/pub" cannot be used with directory "/var/www/magento.loc/pub/media/"`

**Comment by idobarnoam** [comment] 2019-05-13 13:21
Hi @chris-pook Thanks for pointing this and the PR.
we will review and look at how to merge this.

**Comment by eyalktCloudinary** [comment] 2020-09-09 12:40
Closing since the issue is fixed on https://github.com/cloudinary/cloudinary_magento2/pull/34

**Closed by eyalktCloudinary** 2020-09-09 12:40 UTC
