### ISSUE TITLE
Can't set production mode

### ISSUE THREAD

**Issue by killday** [cloudinary/cloudinary_magento2#44] opened 2019-10-29 15:20 UTC
Magento 2.2.0
Module installed using composer ver. 1.10.1

Cloudinary\Cloudinary\Controller\Adminhtml\Cms\Wysiwyg\Images\Upload
		Extra parameters passed to parent construct: $directoryResolver. File: /home/londtser/dev.zenithsecurityco/vendor/cloudinary/cloudinary-magento2/Controller/Adminhtml/Cms/Wysiwyg/Images/Upload.php
Total Errors Count: 1

  [Magento\Framework\Validator\Exception]
  Error during compilation

**Comment by eyalktCloudinary** [comment] 2019-10-30 11:44
@killday Hi, for the investigation purpose, we would need some additional details. Since some of it may contain sensitive information, I took the liberty of opening a support ticket on your behalf. In case we have any insights we'll update this thread as well.

**Comment by silverbrick** [comment] 2020-05-27 17:21
Hello i am facing same issue while using php bin/magento setup:di:compile

**Comment by idobarnoam** [comment] 2020-05-28 08:09
Hi @silverbrick Since handing this might need access to your server, would you be able to open a request at support@cloudinary.com so we could discuss it in detail there?

**Comment by silverbrick** [comment] 2020-05-28 15:12
I Have already mailed and its been a month ( i hope it will take ages for you to fix it )
my request id is (#116477)
I am using magento 2.2.0
Cloudinary\Cloudinary\Controller\Adminhtml\Cms\Wysiwyg\Images\Upload
Extra parameters passed to parent construct: $directoryResolver. File: /home/londtser/dev.zenithsecurityco/vendor/cloudinary/cloudinary-magento2/Controller/Adminhtml/Cms/Wysiwyg/Images/Upload.php
Total Errors Count: 1

**Comment by shirlymanor** [comment] 2020-05-29 18:49
We are checking this issue and will update you in the ticket with any insights early next week.

**Comment by silverbrick** [comment] 2020-05-31 15:10
Steps to reproduce the error :-
Magento version 2.2.0
Installing cloudinary and putting the site in production mode.

**Comment by eyalktCloudinary** [comment] 2020-06-01 09:17
@silverbrick Our dev team could not reproduce the described issue.
Therefore, in order to find the root source of the issue, they would probably need to access your environment. In order to arrange such a thing, we'll continue the discussion on the #116477 support ticket.

**Comment by eyalktCloudinary** [comment] 2020-09-10 07:50
We suspect that the issue was related to the specific client instance (may be related to the steps taken for the module installation). Could not perform a further investigation on the client-side as we did not have access.
Closing for now.

**Closed by eyalktCloudinary** 2020-09-10 07:50 UTC
