### ISSUE TITLE
update to 1.14.6 downgrades cloudinary/cloudinary_php

### ISSUE THREAD

**Issue by donblackowiak** [cloudinary/cloudinary_magento2#83] opened 2021-02-12 02:23 UTC
php -d memory_limit=5G  composer.phar require cloudinary/cloudinary_php:^1.14.6 cloudinary/cloudinary-magento2
Using version ^1.14 for cloudinary/cloudinary-magento2
./composer.json has been updated
Running composer update cloudinary/cloudinary_php cloudinary/cloudinary-magento2
Loading composer repositories with package information
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Lock file operations: 0 installs, 2 updates, 2 removals
  - Removing shrikeh/teapot (v2.3.1)
  - Removing teapot/status-code (v1.1.2)
  - Upgrading cloudinary/cloudinary-magento2 (1.14.4 => 1.14.6)
  - Downgrading cloudinary/cloudinary_php (2.0.2 => 1.20.0)

**Comment by igy** [comment] 2021-02-12 12:27
Hi Don,

We recently upgraded our PHP SDK to a v2.x version, and that's a backwards-incompatible change.

The dependencies of this plugin incorrectly specified no specific versions of cloudinary_php so users adding the plugin were getting an incompatible version installed. That was corrected in 1.14.6 so that the plugin installs the newest 1.x version. 

If our plugin is updated to work with the newer Cloudinary PHP SDK we'll update the dependency again in the appropriate version.

I'm not aware of any associated intentional change regarding teapot/status-code or shrikeh/teapot that are also shown in your output, but if that caused you any problems, may I please ask for some more information about the issue and I can check it for you?

Regards,
Stephen

**Comment by donblackowiak** [comment] 2021-02-12 17:20
Hi Stephen

 

Glad to hear it was intentional. This was all part of a Magento 2.4.2 upgrade test which failed, so I will try again in a couple weeks after all the vendors have worked out their kinks.

 

--Don

 

Don Blackowiak

don@lucuma.com

Cofounder, Lucuma Designs, LLC  

www.Lucuma.com  -  877-858-2862  -  Fax 877-363-0735

proud members of the Fair Trade Federation & 1% for the Planet

**Comment by igy** [comment] 2021-02-12 17:23
Hi Don,

From our side, it should be OK if you're using cloudinary-magento2 1.14.6

I'll close this issue for now, but please do let us know if you encounter any other issues, and apologies for any confusion caused by the versions changing.

Regards,
Stephen

**Closed by igy** 2021-02-12 17:23 UTC
